name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Run application test
        working-directory: ./app
        run: npm test --if-present

      - name: Build Docker image
        run: docker build --no-cache -t devops-webapp:ci .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.WIF_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Google Cloud authentication
        run: |
          gcloud config set project devops-internship-project
          gcloud compute instances describe devops-web-server \
            --zone=us-central1-a

      - name: Prepare deployment directory
        run: |
          gcloud compute ssh devops-web-server \
            --zone=us-central1-a \
            --command="
              sudo rm -rf /home/lumamahesh128/app-deploy &&
              sudo mkdir -p /home/lumamahesh128/app-deploy &&
              sudo chown -R lumamahesh128:lumamahesh128 /home/lumamahesh128/app-deploy
            "

      - name: Copy application files to GCP VM
        run: |
          gcloud compute scp --recurse ./app \
            devops-web-server:/home/lumamahesh128/app-deploy/app \
            --zone=us-central1-a

          gcloud compute scp Dockerfile \
            devops-web-server:/home/lumamahesh128/app-deploy/Dockerfile \
            --zone=us-central1-a

          gcloud compute scp .dockerignore \
            devops-web-server:/home/lumamahesh128/app-deploy/.dockerignore \
            --zone=us-central1-a

      - name: Deploy application to GCP VM
        run: |
          gcloud compute ssh devops-web-server \
            --zone=us-central1-a \
            --command="
              cd /home/lumamahesh128/app-deploy &&
              sudo docker stop devops-webapp-container || true &&
              sudo docker rm devops-webapp-container || true &&
              sudo docker rmi devops-webapp:latest || true &&
              sudo docker build --no-cache -t devops-webapp:latest . &&
              sudo docker run -d \
                --name devops-webapp-container \
                -p 3000:3000 \
                devops-webapp:latest
            "

      - name: Verify deployed application
        run: |
          gcloud compute ssh devops-web-server \
            --zone=us-central1-a \
            --command="curl -I http://localhost:3000"